spring:
  profiles:
    default: dev
  thymeleaf:
    cache: false
    prefix: file:api/src/main/resources/templates/
  web:
    resources:
      cache:
        period: 0
  datasource:
    url: jdbc:mysql://localhost:3306/calendar
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update